### ISSUE TITLE
Weirdness with testing

### ISSUE THREAD

**Issue by dbox** [jenius/axis#195]
@jenius Something odd seems to be happening with testing. Seems to affect most files, but not all. Maybe I'm doing something wrong?

Here is  a super simple example:

Here is `code` untouched, passing:
![1](https://cloud.githubusercontent.com/assets/296130/8491490/5cf32aba-20ff-11e5-9e77-51c5e746d679.jpg)

Let's say for whatever reason I wanted to change the border radius to `13px` instead of `3px`. I change `code.styl` and `test/fixtures/code.css` to both be 13px, but for some reason the test doesn't recognize the change on `code.css`. Still shows up as 3px.
![2](https://cloud.githubusercontent.com/assets/296130/8491500/858893de-20ff-11e5-8557-d40563f1baa4.jpg)

But if I change `code.style` back to 3px, oddly, `code.css` now sees it as `13px`, but clearly still breaking because `code.styl` is `3px`:
![3](https://cloud.githubusercontent.com/assets/296130/8491516/fa31d894-20ff-11e5-9be2-fba2155d1d3f.jpg)

Am I doing something super dumb, or is something off with testing?

**Comment by jenius** [comment]
Checking this out, seems like something is up with the tests. I'll have this fixed shortly, sorry for the super long delay!

**Comment by jenius** [comment]
Ok, just run `npm i` and this should be resolved. Sorry!

**Comment by dbox** [comment]
I'm still having the issue. Can you try changing something simple (like above) and tell me if issue is present for you? It's just not recognizing the changes. Very odd.

**Comment by jenius** [comment]
I did test by making a simple change and confirmed that it was working for me after this modification. Pull from master, remove the node modules folder, reinstall with `npm i` -- is this what you did?

**Comment by dbox** [comment]
yeah, i even tried with a totally fresh repo. Which one did you change so i can try that one? I was trying the example from above

**Comment by dbox** [comment]
but trying to add a dash on the rem(value) also broke it..

**Comment by jenius** [comment]
Just removed the repo, cloned it down fresh, ran npm install, then ran `mocha -g code` to just run the tests for the code mixin, selected randomly. Pass. Changed the stylus file to include another declaration below `code()`, ran tests, failed. Added the other declaration to the css file, passed.

Everything seems to be passing on travis as well. I'm not exactly sure what issue you are experiencing here, I'm not even close to being able to reproduce it. Could you give me specific steps as to what changes you made and how the tests looked after running with specific changes?

**Comment by dbox** [comment]
Thanks for looking into. What happens if you add dash in front of rem(value) ?

**Comment by dbox** [comment]
Basically changing any values in current mixins breaks the testing

**Comment by jenius** [comment]
Just made that change, tests passing locally and on travis:

- https://github.com/jenius/axis/commit/d1f8f4e126eefb3444b3b702b0ec1a0d9461451d
- https://travis-ci.org/jenius/axis/builds/71484652

**Comment by dbox** [comment]
Man. No idea. Anything I do breaks testing. I"ll make a video to show what's happening I guess.

**Comment by jenius** [comment]
Pull down that branch and run the tests. Do they work?

**Comment by dbox** [comment]
What in the world. That passes,  but anything else I touch breaks. happened on Chad's machine too. So weird. I'll post a video for you in a few.

Tried `npm update -g mocha`  too...

**Comment by dbox** [comment]
Also if i take the dash back off it breaks!

**Comment by dbox** [comment]
https://www.dropbox.com/s/0846uju9h3ok5wb/Screenshot%202015-07-17%2016.50.04.png?dl=0

**Comment by dbox** [comment]
This has to be some global thing that i dont have updated or something

**Comment by jenius** [comment]
Honestly, I have no idea... something weird is going on with your machine. Maybe try `npm cache clear` and reinstall deps again?

**Comment by dbox** [comment]
@abstracthat Can you try pulling down current repo and running a simple test and see if it passes? I feel like I'm taking crazy pills.

**Comment by dbox** [comment]
![giphy](https://cloud.githubusercontent.com/assets/296130/8761710/df0b4c86-2d24-11e5-9d5b-eae60397cbdb.gif)

**Comment by abstracthat** [comment]
Pulled. All tests pass for me.

**Comment by dbox** [comment]
did you make a change?

**Comment by abstracthat** [comment]
nope. just pulled and ran `npm test`

**Comment by dbox** [comment]
yeah, make a simple change to something, like changing a value

**Comment by abstracthat** [comment]
I'm not sure which value you want me to change. I tried chaning the rem function test and it still passes fine for me. What's the diff you are trying to change?

```git
diff --git a/test/fixtures/utilities/rem-calculator.css b/test/fixtures/utilities/rem-calculator.css
index 97fa801..705e383 100644
--- a/test/fixtures/utilities/rem-calculator.css
+++ b/test/fixtures/utilities/rem-calculator.css
@@ -1,3 +1,3 @@
 .rem-calculator{
-  font-size: 1.875rem;
+  font-size: 2rem;
 }
diff --git a/test/fixtures/utilities/rem-calculator.styl b/test/fixtures/utilities/rem-calculator.styl
index ba4b8c7..77b49ba 100644
--- a/test/fixtures/utilities/rem-calculator.styl
+++ b/test/fixtures/utilities/rem-calculator.styl
@@ -1,2 +1,2 @@
 .rem-calculator
-  font-size: rem(30px)
+  font-size: rem(32px)
```

**Comment by dbox** [comment]
i think its only happening when I change the actual mixins..

for example (not that i want to do this), can you successfully change the border radius from 1em to 2em on `axis/button.styl` ?

**Comment by dbox** [comment]
```
and B has '1em')
      + expected - actual

                     }
                   }
                   "property": "line-height"
                   "type": "declaration"
      -            "value": "2em"
      +            "value": "1em"
                 }
                 {
                   "position": {
                     "end": {

```

It recognizes that I changed it in mixin but ignores change I did in `button.css`

This is just an example, its happening for w/e I touch. So weird..

**Comment by abstracthat** [comment]
I see. Yes, I can reproduce that same problem. It's like the css is cached.

**Comment by dbox** [comment]
THANK YOU. whew. I'm not crazy.

**Comment by dbox** [comment]
I spent an obscene amount of time trying to figure this out. No idea.

**Comment by dbox** [comment]
Here's the really weird thing. if you change the test css and not the mixin it will still fail. But as soon as you change the mixin it stops recognizing the test css change (as noted in original post way up there)

**Comment by abstracthat** [comment]
It seems to green light the button test as passing during the test... like it's a cached error message or something.

![image](https://cloud.githubusercontent.com/assets/5805280/8761773/6f6369b6-2d30-11e5-86c1-1b669014a57e.png)

**Comment by dbox** [comment]
Yeah... super weird. I just don't really know enough about mocha / testing in general to really troubleshoot it.

**Comment by abstracthat** [comment]
To be honest, I'm not sure what the issue is either. Here's a fork that reproduces the problem as we've been discussing so @jenius can pull and run `npm test` https://github.com/abstracthat/axis-test-error

**Comment by abstracthat** [comment]
and the diff that produces it... https://github.com/abstracthat/axis-test-error/commit/dd1924e25eeb04a4db6857c58ce45591741a83b5

**Comment by dbox** [comment]
Thanks. I should have thought to fork and show the weirdness before, but was just afraid something was hosed on my machine (even though I've tested on 3 dif machines) ha.

**Comment by dbox** [comment]
maybe @declandewet may have an idea

**Comment by jenius** [comment]
Pulled down @abstracthat's repo and ran the tests, they were all passing except for the `additive` one, which tests the `framework` mixin. This mixin includes `button()`, and it's result css has not been updated. I updated the result css in `additive`, and all tests passed.

I can submit a PR to that test repo to demonstrate what I'm talking about if you want. But in this case everything still worked perfectly fine, your changes to that mixin just caused another test to fail because it also included that mixin and you forgot to update its result.

**Comment by abstracthat** [comment]
Ah, I see. Easy oversite. Thanks Jeff!

**Comment by jenius** [comment]
If anyone can produce an issue with the tests that can be reproduced by myself or travis, it would be much easier to debug. At the moment, I still don't see any issues!

**Comment by abstracthat** [comment]
Yeah, I think this can be closed. I bet it was the framework css that was throwing off @dbox.

**Comment by dbox** [comment]
Ah man. Thanks. I'll try it out.

**Comment by dbox** [comment]
Whew. Think that was it. I think up to this point I've only added new tests (which weren't part of framework) so I had no idea that needed to be added there as well.

Thanks for bearing with me @jenius, @abstracthat. Moving on to fixes and new stuff now.
